root = "."
tmp_dir = "tmp"

[build]
cmd = "go run ./cmd/lighthouse/main.go"
include_ext = ["go", "templ"]
exclude_dir = ["tmp", "vendor", ".cache"]
include_dir = ["cmd", "internal", "ui"]
delay = 300
stop_on_error = true